apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gradle
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/displayName: "gradle"
spec:
  description: >-
    This Task tests source using Gradle which is an open-source build automation tool.
    Gradle is designed to be flexible enough to build almost any type of software.
  workspaces:
    - name: output
      description: "Contents processed by Gradle"
  params:
    - name: GRADLEOPTS
      description: "Task applied by built-in and most major Gradle plugins"
      type: array
      default: ["tasks"]
    - name: CONTEXTDIR
      description: "The context directory within the repository for sources"
      default: reviews
  steps:
    - name: gradle-task
      image: gradle:jdk8
      workingDir: "/workspace/output/$(inputs.params.CONTEXTDIR)"
      command: ["gradle"]
      args: ["$(inputs.params.GRADLEOPTS)"]
