apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gradle-build
spec:
  workspaces:
    - name: output
  params:
    - name: contextDir
      description: "The context directory within the repository for sources"
      default: reviews/reviews-application
  steps:
    - name: gradle-build
      image: gradle:jdk8
      workingDir: "/workspace/output/$(inputs.params.contextDir)"
      command: ["gradle"]
      args: ["build"]
    - name: ls-archive
      image: busybox:stable
      command: ["ls"]
      args: ["-ltr", "/workspace/output/$(inputs.params.contextDir)/build/libs"]
