apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab-el
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
        - path: /el/reviews
          pathType: Prefix
          backend:
            service:
              name: el-build-deploy-reviews-listener
              port:
                number: 8080
